from secure import *

DEBUG = True

SQLALCHEMY_DATABASE_URI = f'mysql://{USERNAME}:{PASSWORD}@{SERVER}/{DB}'
SQLALCHEMY_TRACK_MODIFICATIONS = True

SECRET_KEY = FLASK_SECRET
BABEL_DEFAULT_LOCALE = 'pt'